from selenium import webdriver
from selenium.webdriver.common.by import By
import time

drive=webdriver.Edge("c:\\Drivers\\edgedriver_win64\\msedgedriver.exe")
driver=webdriver.Edge("c:\\Drivers\\edgedriver_win64\\msedgedriver.exe")
driver.implicitly_wait(10)
driver.maximize_window()
driver.get("https://localtaxicloud.com/#/localtaxi/signup")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[2]/input").send_keys("alladi cloud solution")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[3]/input").send_keys("alladi")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[4]/input").send_keys("9390685200")
driver.find_element(By.ID,"mat-input-0").send_keys("10/10/2024")
driver.find_element(By.ID,"mat-input-1").send_keys("12/10/2024")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[7]/input").send_keys("meeniga")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[8]/input").send_keys("kumar")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[9]/input").send_keys("tharun")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[10]/input").send_keys("KPHB")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[11]/input").send_keys("Hyderabad")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[12]/select").send_keys("India")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[13]/select").send_keys("Telangana")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[14]/select").send_keys("commissionweekly")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[15]/input").send_keys("10000")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[17]/input").send_keys("518401")
driver.find_element(By.ID,"mat-mdc-checkbox-1-input").click()
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[25]/input").send_keys("9876543212")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[26]/input").send_keys("tharunmeeniga@gmail.com")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[27]/input").send_keys("kotak")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[28]/input").send_keys("3245453679")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[29]/input").send_keys("KKBK0007804")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[30]/input").send_keys("848477447")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[31]/input").send_keys("tharunmeeniga@gmail.com")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[32]/input").send_keys("Tharun@123")
driver.find_element(By.XPATH,"/html/body/app-root/div/div/app-sign-up/div/form/div[33]/input").send_keys("Tharun@123")
#driver.find_element(By.ID,"companyLogo").click()
driver.find_element(By.CLASS_NAME,"submit-container").submit()

time.sleep(10)